- src/components/Signup/Signup.test.tsx
- src/components/Signup/Signup.tsx
- src/components/Signup/SignupContainer.tsx
- src/components/Signup/styles.ts
- src/pages/SignupPage/index.tsx
- src/routes/Router.tsx
- 회원가입 페이지 레이아웃을 추가 한다.
- 레이아웃 관련 테스트 파일을 추가 한다.
- Router에 SignupPage을 추가 한다.
closes #21 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
테스트 결과
- 회원가입 버튼을 눌렀을 때 `useLocation` 이나 `useHistory` 를 사용하여 정확히 페이지가 변경되었는지 테스트 하고 싶었는데 방법을 아직 찾지 못했습니다. 그래서 이 부분은 일단 생략하고 진행하였습니다. 추후 방법을 찾게되면 따로 공지하겠습니다.
> DVT-#21 회원가입 페이지 레이아웃 추가

- src/components/Login/Login.test.tsx
- src/components/Login/Login.tsx
- src/components/Login/LoginContainer.test.tsx
- src/components/Login/LoginContainer.tsx
- src/components/Login/styles.ts
- src/components/Login/types.ts
- src/utils/constants.ts
- tsconfig.json
로그인 페이지의 이메일, 비밀번호의 유효성을 체크한다.
closes #27 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
테스트 결과
- formik, yup 사용하여 유효성 체크
- constants.ts 추가
- tsconfig.json에 lib 추가 (async, await 사용을 위함)
- 지금은 이메일만 입력하여도 비밀번호까지 정합성 체크를 같이 하는데 이 부분은 공식문서를 더 읽어보고 리펙토링 할 예정입니다.
- 테스트할 때 `waitFor`를 사용해서 그런가 시간이 좀 걸리는것 같습니다. (waitFor를 사용하지 않고 change 이벤트를 컨트롤 하려고 하면 formik에서 에러가 발생하더라구요 아직 정확한 원인은 파악하지 못했습니다. 😭 쉽지않네요..)
> DVT-#27 로그인 페이지 폼 유효성 체크

- src/assets/theme.ts
- src/components/MyProfile/MyProfile.tsx
- src/components/base/Input/index.tsx
- src/components/base/Input/styles.ts
- src/components/base/Input/types.ts
Input Base 컴포넌트 개발
closes #67 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
- customStyle 속성을 사용해서 자유롭게 디자인 할 수 있게 구조를 잡아봤는데 코드가가 깔끔하지 않은 느낌이 듭니다.. 더 좋은 방법이 분명 있을 것 같은데 지금은 생각이 안나는 것 같습니다. 어떤식으로 해야 더 깔끔할지 여러분들의 자문을 구하고 싶네요 ㅠㅠㅠ 코드가 너무 마음에 들지 않습니다
```tsx
import { StyledInput, CustomStyledInput } from "./styles";
import { IProps } from "./types";
const Input = ({
type,
name,
value,
checked,
disabled,
required,
readOnly,
placeholder,
autoComplete,
customStyle,
onChange,
}: IProps) => {
// 1. type부터 시작해서 onChange 까지 props들을 CustomStyledInput, StyledInput 둘다 선언하는게 너무 지저분한거 같아요...
return customStyle ? (
<CustomStyledInput
type={type}
name={name}
value={value}
checked={checked} …
```
> DVT-#67 Input Base 컴포넌트 개발

- fixtures/selectDatas.ts
- fixtures/userList.ts
- src/assets/media.ts
- src/components/CommentButton/CommentButton.tsx
- src/components/LikeButton/LikeButton.tsx
- src/components/MyProfile/MyProfile.tsx
- src/components/ProfileCard/ProfileCard.tsx
- src/components/UserCard/styles.ts
- src/components/UserList/UserList.tsx
- src/components/UserList/UserListContainer.tsx
- src/components/UserList/styles.ts
- src/components/UserList/types.ts
- src/components/base/Button/styles.ts
- src/components/base/Input/index.tsx
- src/components/base/Input/types.ts
- src/constants/common.ts
- src/pages/UserListPage/index.tsx
- src/routes/Router.tsx
- src/routes/customRoutes/PrivateRoute.tsx
closes #85 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
움짤 자꾸 용량초과돼서 사진을 임시로 올리겠습니다
- 백엔드 API가 구성되지 않아 레이아웃 작업 진행
- `MBTI`는 표시하지 않았습니다. 카드에 너무 많은 정보가 있으면 난잡(?) 해지는 것 같아요 ㅠㅠ
- `(메인화면)` 부분은 @datalater 의 확인이 필요합니다 🙏
- (메인화면) base/Button에 `display: flex` 추가 -> 정렬을 위함
- (메인화면) CommentButton, LiknkButton -> `verticalAlgin: text-top` 제거 -> 정렬을 위함
- (메인화면) UserCard -> `padding-bottom` 추가 (위 변경사항에 대해 스크롤이 생겨 padding 값을 줌)
- MBTI 데이터 수정
- breakpoints 추가 (팀원간 협의 후 사용) -> max, min 둘 중 하나로 통일해서 사용하는 게 좋을 것 같습니다. 기준은 [여기](https://devfacts.com/media-queries-breakpoints-2021)를 참조했습니다.
```ts
// 기존
export const breakpoints = {
maxMobile: "@media screen and …
```
> DVT-#85 데둥이 소개 페이지 리스트 레이아웃

- package.json
- src/assets/media.ts
- src/components/Login/LoginContainer.tsx
- src/components/ProfileCard/ProfileCard.tsx
- src/components/UserDetail/Comment/index.tsx
- src/components/UserDetail/Comment/styles.ts
- src/components/UserList/UserList.tsx
- src/components/UserList/UserListContainer.tsx
- src/components/UserList/styles.ts
- src/components/UserList/types.ts
- src/constants/common.ts
- src/hooks/useUserInfiniteQuery.ts
- src/utils/apis/introductions.ts
- yarn.lock
데둥이 소개 리스트 무한 스크롤
closes #105 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/52060742/146390106-1575bda2-bee9-41ba-b12a-40394b31b0e6.mp4
- 데둥이 리스트 좋아요 버튼 눌렀을 때 상세페이지로 라우팅 
- 원래 좋아요를 붙이려고 했으나 좋아요 여부를 알 수 있는 liked 필드가 리스트에 없음 
- 무한 스크롤 1번 조회 개수는 19개로 함
- 그 이유는 리스트의 형태가 grid 형태의 카드모양이기 때문에 초기에 보여지는 데이터의 수가 많을 수도 있음
- 데둥이 상세페이지 댓글 작성자 프로필 cursor 제거 
- 원래 데둥이 상세페이지의 댓글에 작성자 프로필을 클릭하면 상대방의 상세 화면으로 가게 하려고 했으나 댓글에 introductionId가 없어 상세화면으로 가지 못함
- 좋아요 시 Lottie 일단 보류함 값의 변화에 따라서 애니메이션이 고르지 못하게 나오는 현상이 있어서 추후 적용할 예정
> DVT-#105 데둥이 소개 무한스크롤

- src/atoms/sidebarVisible.ts
- src/pages/GatherClubPage/index.tsx
- src/pages/GatherDetailPage/index.tsx
- src/pages/GatherPage/index.tsx
- src/pages/GatherProjectPage/index.tsx
- src/pages/GatherStudyPage/index.tsx
- src/pages/LoginPage/index.tsx
- src/pages/MainPage/index.tsx
- src/pages/MyProfilePage/index.tsx
- src/pages/SignupPage/index.tsx
- src/pages/UserDetailPage/index.tsx
- src/pages/UserListPage/index.tsx
- src/pages/UsersMapPage/index.tsx
- src/template/DefaultTemplate.tsx
페이지별 사이드바 visible 처리
closes #110 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
- `src/pages` 하위에 있는 페이지 컴포넌트 들에 모두 추가했습니다. 추후 페이지 컴포넌트가 생긴다면 아래 내용을 꼭 추가해 주세요
```tsx
import { useRecoilState } from "recoil";
import { sidebarVisibleState } from "../../atoms/sidebarVisible";
const [isShowSidebar, setShowSidebar] = useRecoilState(sidebarVisibleState);
useEffect(() => {
setShowSidebar(true);
}, [isShowSidebar, setShowSidebar]);
```
- 원리는 이렇습니다. `sidebarVisibleState` 라는 atom을 만들고 해당 페이지들이 마운트 될 때 각자에 맞는 사이드바 보여짐 상태를 변경 -> DefaultTemplate에서 `sidebarVisibleState`를 구독하고 있기 때문에 처리 가능
- 더 좋은 아이디어가 있다면 마구 알려주세요!
> DVT-#110 페이지별 사이드바 visible 처리

- src/atoms/topbarVisble.ts
- src/components/Main/Main.test.tsx
- src/components/Main/Main.tsx
- src/pages/LoginPage/index.tsx
- src/pages/MainPage/index.tsx
- src/pages/MapgakcoMapPage/index.tsx
- src/pages/MyProfilePage/index.tsx
- src/pages/SignupPage/index.tsx
- src/pages/UsersMapPage/index.tsx
- src/template/DefaultTemplate.tsx
- src/template/styles.ts
탑바를 디폴트 템플릿으로 위치 변경한다. 각 페이지마다 유동적으로 탑바를 보여줄지를 결정한다.
closes #135 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
예정)
공통으로 가시성 옵션을` true`로 넣은 탑바를 로그인 페이지에서는 보여주지 않습니다.
- 사이드바와 마찬가지 로직으로 탑바의 가시성 여부가 결정됩니다.
- 탑바의 백그라운드 색상이 문제가 됩니다. 와이어프레임 기준으로 작성되었는데 현재 다른 페이지와 배경 색상이 튀는 부분이 있어서 머지하기 전에 팀원들과 논의가 필요합니다.
- 모집게시판 페이지의 경우 뿡치의 작업과 충돌나지 않도록 변경하지 않았습니다. 각자 작업한 페이지에 적용이 안된 부분은 직접 적용해주세요.
> DVT-#135 탑바를 디폴트 템플릿으로 위치 변경

- src/components/Comment/Comment.tsx
- src/components/GatherDetail/GatherDetail.tsx
- src/components/GatherDetail/GatherDetailContainer.tsx
- src/components/GatherDetail/styles.ts
- src/components/GatherDetail/types.ts
- src/components/GatherList/GatherList.tsx
- src/hooks/useCloseGather.ts
- src/hooks/useCreateGatherComment.ts
- src/hooks/useDeleteComment.ts
- src/hooks/useDeleteGather.ts
- src/hooks/useEditGatherDetail.ts
- src/utils/apis/gather.ts
모집게시글 상세 페이지의 전체적인 레이아웃 변경과 모집 게시글 수정, 모집 마감 API를 연동한다.
closes #129 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
**모집 게시글 작성자가 상세 페이지에 접속했을 떄**
**작성자가 아닌 일반 유저가 접속했을 때**
- 댓글 관련 API는 댓글 수정 빼고 모두 연동했지만 레이아웃을 수정해야해서 댓글 부분은 좀 이상하게 보입니다!(대댓글이 대댓글처럼 안보인다)
> DVT-#129 모집 게시글 상세 페이지 레이아웃 수정 및 모집 마감, 게시글 수정 API 연동

- src/atoms/topbarBgColor.ts
- src/components/Main/styles.ts
- src/pages/AdminPage/index.tsx
- src/pages/GatherClubPage/index.tsx
- src/pages/GatherPage/index.tsx
- src/pages/GatherProjectPage/index.tsx
- src/pages/GatherStudyPage/index.tsx
- src/pages/MainPage/index.tsx
- src/pages/MyGatherPage/index.tsx
- src/pages/MyProfilePage/index.tsx
- src/pages/UserListPage/index.tsx
- src/template/DefaultTemplate.tsx
- src/template/styles.ts
페이지마다 탑바 색상을 유동적으로 관리할 수 있도록 변경한다
closes #141 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
> DVT-#141 탑바 스타일을 전역 상태로 관리

- package.json
- src/components/Admin/Admin.tsx
- src/components/Admin/styles.ts
- src/components/Signup/Signup.tsx
- src/components/Signup/SignupContainer.test.tsx
- src/constants/admin.ts
- src/hooks/useCopyClipboard.ts
- src/hooks/useCustomToast.ts
- src/hooks/useMutationInviteLink.ts
- src/hooks/useMyProfile.ts
- src/hooks/useQueryCheckValidLink.ts
- src/hooks/useQueryInviteLink.ts
- src/index.tsx
- src/routes/Router.tsx
- src/utils/apis/admin.ts
- src/utils/yups/admin.ts
- yarn.lock
회원가입 링크 생성 API 연동
closes #140 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- .env 파일에 `DOMAIN=http://localhost:8000/` 추가해주셔야 합니다. 현재 초대링크 복사하는 부분에서 사용하고 있어요!!
> DVT-#140 회원가입 링크 생성 API 연동

- src/components/GatherDetail/GatherDetail.tsx
- src/components/GatherDetail/styles.ts
- src/components/GatherList/GatherList.tsx
- src/components/GatherList/styles.ts
- src/components/MyGather/MyGather.tsx
- src/components/MyGather/MyGatherContainer.tsx
- src/components/MyGather/styles.ts
- src/components/PeriodText/index.tsx
- src/components/ProfileBox/ProfileBox.tsx
- src/constants/categoryName.ts
- src/hooks/useMyAppliedGather.ts
- src/hooks/useMyPostingGather.ts
- src/types/gather.ts
- src/utils/apis/gather.ts
내 모임 관리 페이지에 필요한 API들을 연동한다.
closes #127
> PR 양식 체크리스트
> 구현한 내용 체크리스트
**내 모임 관리 페이지**
**창이 줄었을 때**
- 내 모집을 보여줄 때 맵각코도 같이 보여주기 때문에 맵각코 속성들을 gather에 추가했습니다
- 기존에 내 모임 관리 페이지의 반응형을 위해 만든 구조에 문제가 있어서 수정했습니다
- 창이 줄었을 때 등록한 모임을 클릭했다가 창이 늘어나면 신청한 모임에 등록한 모임의 리스트가 뜨는 문제였습니다
- 개설 -> 등록으로 명칭 수정
- 유저 디폴트 이미지 추가
- 가시성을 위해 모집기간에 공백 추가
- 내 모임 관리 페이지 타이틀
> DVT-#127내 모임 관리 페이지 API 연동

- fixtures/userInfo.ts
- src/assets/theme.ts
- src/components/Mapbox/Mapbox.tsx
- src/components/Mapbox/mapgakcoOverlay.scss
- src/components/MapgakcoMap/MapgakcoDetail/index.tsx
- src/components/MapgakcoMap/MapgakcoDetail/styles.ts
- src/components/MapgakcoMap/MapgakcoMap.tsx
- src/components/MapgakcoMap/MapgakcoMapContainer.tsx
- src/components/MapgakcoMap/MapgakcoMarker.tsx
- src/components/MapgakcoMap/UserMarker.tsx
- src/components/base/Modal/index.tsx
- src/hooks/useClickAway.ts
- src/hooks/useMapgakcos.ts
- src/template/DefaultTemplate.tsx
- src/template/styles.ts
- src/types/mapTypes.ts
- src/utils/apis/index.ts
- src/utils/apis/mapgakco.ts
- src/utils/apis/mocks/index.ts
- src/utils/apis/mocks/mapgakcos.ts
- src/utils/date.ts
- src/utils/map/overlay.ts
맵각코 페이지에서 맵각코 조회 기능을 추가한다.
closes #115 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/146674929-78530c9d-4553-459d-a77c-197abffa77f1.mov
- 아직 작업이 끝나지 않았는데 PR 범위가 커져서 올립니다. 그러다 보니 주석이 있거나 정제되지 않은 코드들이 있는데 머지되면 이어서 작업하겠습니다.
> DVT-#115 맵각코 페이지 맵각코 조회 기능 추가

- src/App.tsx
- src/components/Login/LoginContainer.tsx
- src/components/MyProfile/MyProfileContainer.tsx
- src/components/Signup/SignupContainer.tsx
- src/components/UserList/UserListContainer.tsx
- src/hooks/useCustomQueryClient.ts
- src/hooks/useIntroduction.ts
- src/hooks/useMutationMapgakcoRegister.ts
- src/hooks/useMutationUserDeleteLike.ts
- src/hooks/useMutationUserLike.ts
- src/hooks/useMutationUserModifyComment.ts
- src/hooks/useQueryCheckValidLink.ts
- src/hooks/useUserInfiniteQuery.ts
react-query `onError` 핸들러를 전역으로 관리한다.
closes #146 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
@datalater @ono212 
- react-query의 `useQuery`, `useMutation`의 `onError` 처리를 전역에서 하도록 했습니다. (src/hooks/useCustomQueryClient.ts) 그래서 기존에 사용하셨던 `onError` 부분을 지워주셔도 됩니다!!! 일단 제가 작업한 query, mutation만 진행했으니 각자 작업하신 부분은 꼭! 지워주세요
> DVT-#146 react-query 에러 처리

- src/components/MapgakcoRegister/index.tsx
- src/components/MapgakcoRegister/stlyes.ts
- src/components/MyProfile/MyProfile.tsx
- src/components/MyProfile/styles.ts
- src/components/UserDetail/Comment/index.tsx
- src/components/UserDetail/Comment/styles.ts
- src/components/UserDetail/UserDetail.tsx
- src/components/UserDetail/styles.ts
- src/components/UserList/styles.ts
레이아웃 피드백 반영
closes #154 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 내 프로필
- 데둥이 소개 페이지
- 맵각코
- 마이프로필
https://user-images.githubusercontent.com/52060742/146709894-4fbc6d51-3f2d-4d2f-8793-9c8953c447b5.mp4
- 데둥이 상세 페이지
https://user-images.githubusercontent.com/52060742/146709588-0eb0397b-282e-49a7-b84a-974ee92154d0.mp4
- 맵각코 등록 모달 height 증가
-
> DVT-#154 레이아웃 피드백 반영

- .babelrc
- package.json
- src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx
- src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/index.tsx
- src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx
- src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/styles.ts
- src/components/MapgakcoMap/MapgakcoMapContainer.tsx
- src/constants/api.ts
- src/constants/coords.ts
- src/constants/index.ts
- src/hooks/useMapgakcoDetailQuery.tsx
- src/hooks/useMapgakcos.ts
- src/hooks/useMutationMapgakcoPatch.ts
- src/types/mapgakco.ts
- src/utils/apis/index.ts
- src/utils/apis/mapgakco.ts
- webpack.config.js
- yarn.lock
맵각코 페이지에서 조회 API를 연동한다
closes #162 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/146772152-96655930-9f55-4906-adfa-3f6fca55de6d.mov
- 이모션 클래스 네임을 컴포넌트 경로로 자동 레이블링 하도록 세팅 되었습니다. 이제 스타일링 개발이 훨씬 편해졌습니다...!! 
- 개발 환경에서만 컴포넌트 이름을 볼 수 있고 운영 환경에서는 보이지 않습니다.
> DVT-#162 맵각코 페이지 조회 API 연동

- src/components/Mapbox/customOverlayMarker.scss
- src/components/MapgakcoMap/MapgakcoMap.tsx
- src/components/MapgakcoMap/MapgakcoMapContainer.tsx
- src/components/MapgakcoMap/UserMarker.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/styles.ts
- src/components/UserImageAndDropdown/UserImageAndDropdown.test.tsx
- src/components/UserImageAndDropdown/UserImageAndDropdown.tsx
- src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx
- src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx
- src/components/UsersMap/UsersMap.tsx
- src/components/UsersMap/UsersMapContainer.tsx
- src/constants/api.ts
- src/hooks/useHover.ts
- src/hooks/useUsersLocationsFormik.ts
- src/hooks/useUsersLocationsQuery.ts
- src/types/userLocation.ts
- src/utils/apis/index.ts
- src/utils/apis/user.ts
- src/utils/map/overlay.ts
맵각코 페이지에서 데둥이 조회 API 연동한다.
closes #166 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 사용자가 보고 있는 페이지와 일치하는 사이드바 메뉴에 배경색 적용
- 데둥여지도에 필터링 기능 추가
- 데둥여지도 부분은 피드백 내용과 API 명세가 일치하지 않는 부분이 있어 확인 후 추가 작업이 있을 수 있습니다.
- 데둥여지도에서 사용자의 기수, 코스별로 필터링하는 부분은 데둥이 소개에 있는 컴포넌트를 그대로 재활용 하였습니다. 따라서 데둥여지도 페이지의 해당 컴포넌트가 업데이트 될 경우 함께 업데이트 될 수 있습니다.
> DVT-#166 맵각코 페이지에서 데둥이 조회 API 연동

- src/components/UserImageAndDropdown/UserImageAndDropdown.tsx
유저 프로필 이미지에 마우스 오버했다가 드랍다운 메뉴로 커서를 이동했을 때 드랍다운 메뉴가 사라지는 버그를 해결한다.
closes #175 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/146888976-48239f1f-bbdc-465a-9e72-2b1ebc6195fa.mov
없음
> DVT-#174 유저 드랍다운 메뉴 버그 해결

- package.json
- src/assets/theme.ts
- src/components/Admin/Admin.tsx
- src/components/GatherDetail/Comment/index.tsx
- src/components/Main/Main.test.tsx
- src/components/Main/styles.ts
- src/components/MapgakcoRegister/index.tsx
- src/components/MapgakcoRegister/stlyes.ts
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/menuRoutes.ts
- src/components/Sidebar/styles.ts
- src/components/UserCardList/UserCardList.test.tsx
- src/components/UserCardList/UserCardList.tsx
- src/components/UserDetail/Comment/index.tsx
- src/components/UserDetail/UserDetail.tsx
- src/components/UserDetail/types.ts
- src/hooks/useDayjs.ts
- src/hooks/useMutationInviteLink.ts
- src/pages/MainPage/index.test.tsx
- yarn.lock
레이아웃 관련 피드백 반영
closes #172 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- dayjs를 useDayjs훅으로 분리
- 초대링크 생성 후 toast 메세지 띄우는 로직 수정
- 기존에는 생성되면 무조건 띄웠는데 성공했을 때만 띄우도록 변경
- 맵각코 등록 모달 등록 버튼 색상 파란색으로 수정
- 댓글 개수 표시
- 사이드바 스터디, 동아리, 프로젝트 1 depth 안으로 넣어서 구분
- 메인화면에서 자기소개 클릭시 상세화면으로 이동
- 메인화면 자기소개 가로 스크롤
- 사이드바 스터디, 동아리, 프로젝트 구분
- 댓글 개수 표시
- 가로스크롤
https://user-images.githubusercontent.com/52060742/146865697-dea30ce9-6770-4ad5-a92d-63b19c9f798e.mp4
- dayjs를 useDayjs훅으로 분리하였습니다. 혹시나 다른곳에서 dayjs를 사용중 이라면 훅으로 변경해 주세요
- @ono212 모집게시판 댓글에는 제가 코드 수정해놨습니다. 댓글 개수 또한 모집게시판 댓글 코드에도 적용해놨습니다.
- 댓글에 dayjs의 `fromNow`를 사용하여 댓글을 작성한 시간을 보여주고 있는데 서버와 브라우저의 시간차이가 약간 있어서 …
> DVT-#172 레이아웃 다듬기

- src/components/UserCardList/UserCardList.tsx
메인화면 자기소개 가로 스크롤에서 좌우로 흔들리는 레이아웃 버그해결
closes #194 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
Link: https://www.npmjs.com/package/react-scroll-horizontal
자기소개 개수가 적어서 부모 컴포넌트보다 너비가 작을 때 흔들리는 현상이 사라졌습니다.
없음
> DVT-#194 메인화면 자기소개 흔들리는 레이아웃 버그해결

- src/components/MapgakcoMap/MapgakcoMap.tsx
- src/components/MapgakcoMap/PlaceSearchForm.tsx
맵각코 페이지에서 검색을 마치면 검색 결과 창 없애기
closes #203 
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/147891872-6209d328-cedf-4ecf-a38a-f67ba7af96dc.mov
- 맵각코 페이지에서 검색을 마치면 검색 결과 창 없애기
- 뷰포트가 줄어들어도 맵각코 페이지 버튼의 글씨가 두 줄로 뭉개지지 않도록 수정
- `whiteSpace` 속성은 `React.CSSProperties` 타입에서 제공하지 않는 타입이라 타입 단언을 사용하여 타입 오류를 해결합니다.
> DVT-#203 맵각코 페이지에서 검색을 마치면 검색 결과 제거

- src/components/UserDetail/Comment/index.tsx
대댓글 값 버그 수정
closes #207 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
- onSubmit 후 `resetForm()`을 하였는데 이 부분때문에 이전값으로 되돌아 갔음. 제거하여 해결
> DVT-#207 대댓글 값 버그 수정
