prgrms-web-devcourse/Team_BbungCles_Devnity_FE

.vscode/settings.json, index.html, package.json, tsconfig.json, yarn.lock
카카오맵 라이브러리 설치 및 테스트를 했다.
closes #5 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#5 카카오맵 라이브러리 추가

.github/CODEOWNERS
PR 리뷰어를 자동으로 설정하도록 [CODEOWNERS 파일](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)을 생성합니다.
closes #7 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#7 PR 리뷰어 자동 설정

src/App.tsx, src/assets/theme.ts, src/types/emotion.d.ts
이모션으로 전역 스타일 테마를 설정한다.
closes #10 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#10 이모션으로 전역 스타일 테마 설정

package.json, src/App.tsx, src/index.tsx, src/pages/MainPage/index.tsx, src/routes/Router.tsx, yarn.lock
라우터 초기 설정을 했다.
closes #9 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 라우터 초기 설정
- react-router-dom 라이브러리 추가
없음
없음
=> DVT-#9 라우터 초기 설정

package.json, yarn.lock
formik, yup, react-query, recoil 설치한다.
- formik : 폼 라이브러리
- yup : 폼 유효성 검사 라이브러리
- recoil : 상태관리 라이브러리
- react-query : 비동기 제어 라이브러리
closes #13 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#13 formik, yup, react-query, recoil 설치

tsconfig.json
타입스크립트 설정 파일에 테스팅에 필요한 타입을 추가한다.
closes #18 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#18 타입스크립트 설정 파일에 테스팅에 필요한 타입 추가

src/assets/theme.ts
이모션으로 설정한 전역 스타일을 자동완성이 되도록 타입을 지정한다.
closes #25 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#25 이모션으로 설정한 전역 스타일을 자동완성이 되도록 타입 지정

index.html, src/assets/globalStyles.ts, src/index.tsx
모든 브라우저에서 동일한 UI가 렌더링되도록 `reset.css`로 유저 에이전트 스타일 시트를 초기화하고,  프로젝트 전체에 스타일을 적용하기 위한 글로벌 스타일을 추가합니다.
closes #23 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
초기화한다.
추가한다.
- reset.css를 index.html에서 불러옴으로써 유저 에이전트 스타일 시트를 초기화합니다.
- HTML 표준 엘리먼트에 공통적으로 적용할 스타일은 글로벌 스타일에 추가합니다.
=> DVT-#23 reset.css 및 글로벌 스타일 추가

.github/workflows/ci.yml, package.json
closes #31 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
틺원들과 함께 모여서 스텝바이스텝으로 진행했습니다.
=> DVT-#30 코드 병합 전 자동으로 테스트 실행 및 린트 검사를 위해 CI 구축

src/assets/theme.ts, src/types/emotion.d.ts
객체의 프로퍼티를 사용할 때 IDE에서 자동완성을 지원하기 위해 사용했던 const assertion(`as const`)이 불필요하다는 것을 알게 되어 제거한다.
closes #38 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#38 불필요한 타입 선언 제거

package.json, src/App.tsx, src/components/Signup/Signup.tsx, src/components/Signup/SignupContainer.test.tsx, src/components/Signup/SignupContainer.tsx, src/components/Signup/styles.ts, src/components/Signup/types.ts, src/utils/apis/axiosInstance.ts, src/utils/apis/signup.ts, src/utils/constants.ts, src/utils/yups/signup.ts, yarn.lock
회원가입 페이지에서 axios + react-query를 사용하여 API를 연동한다.
closes #36 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 회원가입 백엔드 API가 아직 구성되지 않아 화면 레이아웃 작업 진행
=> DVT-#36 회원가입 API 연동

src/assets/globalStyles.ts
프로젝트에서 사용할 웹 폰트로서 스포카 한 산스 네오(Spoqa Han Sans Neo)를 추가한다.
closes #44 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- `index.html`에서 불러오는 `reset.css`의 우선순위가 더 높으므로 `font-family` 값에 `!important` 키워드를 추가한다.
=> DVT-#44 웹 폰트 스포카 한 산스 추가

src/components/ProfileBox/ProfileBox.tsx
ProfileBox컴포넌트에서 쓰이는 Text 컴포넌트의 prop을 수정한다.
closes #50 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
=> DVT-#50 ProfileBox 오류 수정

src/components/Sidebar/Sidebar.test.tsx, src/components/Sidebar/SidebarContainer.test.tsx, src/components/Sidebar/menuRoutes.ts, src/components/Signup/SignupContainer.tsx, src/components/UserDropdownMenu/UserDropdownMenu.test.tsx, src/components/UserDropdownMenu/menuRoutes.ts, src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx, src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx, src/constants/index.ts, src/constants/routes.ts, src/routes/Router.tsx, src/routes/customRoutes/PrivateRoute.tsx, src/routes/customRoutes/RestrictRoute.tsx
라우트 경로 상수화를 한다.
closes #68 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음.
- PrivateRoute, RestrictRoute any 사용 -> 추후 수정 필요
=> DVT-#68 라우트 경로 상수화

src/components/MyProfile/MyProfileContainer.tsx
카카오맵 센터포지션 null 체크
closes #79 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
=> DVT-#79 카카오맵 센터포지션 null 체크

.eslintrc.js, src/App.tsx, src/atoms/index.ts, src/atoms/user.ts, src/components/Main/Main.test.tsx, src/components/MyProfile/types.ts, src/components/UserImageAndDropdown/UserImageAndDropdownContainer.test.tsx, src/components/UserImageAndDropdown/UserImageAndDropdownContainer.tsx, src/pages/MainPage/index.test.tsx, src/template/DefaultTemplate.tsx
자신의 정보를 전역에서 확인할 수 있도록 recoil 사용
closes #87 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
- 사용자의 토큰이 유효한 상태이고, 브라우저를 새로 킨 상태에서 로그인 페이지 외에 다른 페이지로 직접 접근했을 경우 recoil에 자신의 정보를 세팅하는 로직을 `DefaultTemplate.tsx`에 설정했습니다.
- 더 좋은 방법이 있다면 조언 부탁드려요! 😭
- 시간만 더 많았으면 깊게 보고싶은데...
```tsx
import { globalMyProfile } from "../atoms";
const [globalMyProfile, setGlobalMyProfile] = useRecoilState(globalMyProfile);
```
사용방법은 useState와 동일하게 사용할 수 있습니다.
=> DVT-#87 자신의 정보 recoil로 관리

src/components/LikeButton/LikeButton.tsx, src/components/LikeButtonAndText/LikeButtonAndText.tsx, src/components/ProfileCard/ProfileCard.tsx, src/components/UserDetail/Comment/index.tsx, src/components/UserDetail/Comment/styles.ts, src/components/UserDetail/UserDetail.tsx, src/components/UserDetail/UserDetailContainer.tsx, src/components/UserDetail/styles.ts, src/components/UserDetail/types.ts, src/components/UserList/UserList.tsx, src/components/UserList/UserListContainer.tsx, src/components/UserList/styles.ts, src/components/UserList/types.ts, src/components/base/MarkdownEditor/index.tsx, src/constants/common.ts, src/constants/routes.ts, src/hooks/useIntroduction.ts, src/hooks/useMyProfile.ts, src/pages/UserDetailPage/index.tsx, src/routes/Router.tsx, src/template/DefaultTemplate.tsx, src/utils/apis/introductions.ts
closes #86 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/52060742/146126129-524ec574-2298-4196-9221-f2f1d4eeff23.mp4
- 상세 조회 API는 mocky로 연결했음
- 시간이 남는다면 프로필 사진 및 기본 정보를 명함의 형태로 디자인 해보고 싶네요! ㅠㅠ
=> DVT-#86 데둥이 소개 페이지 상세

.eslintrc.js, .gitignore, cypress.json, cypress/fixtures/signupFormData.json, cypress/integration/login.spec.ts, cypress/integration/signup.spec.ts, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, cypress/tsconfig.json, jest.config.js, package.json, src/App.tsx, yarn.lock
단위 테스트나 통합 테스트로는 할 수 없는 기능을 테스트하기 위해 E2E 테스트 도구인 Cypress를 설치한다.
closes #88 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/146320304-b6ad146b-6cc1-482d-b4ef-efffaa4f605d.mp4
- Cypress open 테스트 동작 화면입니다.
- 참고로 위 영상은 Cypress가 자동으로 만들어준 영상입니다.
- 로그인 페이지가 뜨는데 6초 이상이 걸리네요. 추후 번들 분석 리포트도 보고 lighthouse 같은 성능 지표를 사용해서 개선해야겠습니다🥲
없음
---
**2021.12.16.15:49:**
Cypress 폴더에 주석이 가득한 문서들이 있습니다. 이 문서들은 Cypress 설치 후 실행하면 자동으로 생성되는 스캐폴딩 문서입니다. 처음 사용해보는 거라 잘못 건드렸다가 오동작할 수도 있고 나중에 테스트 코드를 작성하면서 참조할 가능성도 있어 보여서 남겨두었습니다!
=> DVT-#88 E2E 테스트를 위한 Cypress 설정

fixtures/gather.ts
`fixtures/gather.ts`에서 `import` 구문에 있는 파일명 오타를 수정한다.
```ts
// as is
import { Gather } from "../src/types/Gather";
// to be
import { Gather } from "../src/types/gather";
```
closes #116 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
백엔드팀도 만든 기능이 잘 되고 있는지 확인할 수 있게 하고 우리도 배포 버전이 잘 되는지 확인도 할 겸 Vercel에 배포해보다가 알게 되었습니다🥲
린트로 못 걸러내고 있었네요 뭐지..🤔
=> DVT-#116 파일명 케이스 오타 수정

src/components/MyProfile/MyProfile.tsx, src/components/Signup/styles.ts, src/components/UserDetail/Comment/index.tsx, src/components/UserDetail/UserDetail.tsx, src/components/UserDetail/styles.ts, src/components/base/Input/index.tsx, src/components/base/Input/types.ts, src/constants/common.ts, src/constants/signup.ts, src/utils/yups/login.ts, src/utils/yups/signup.ts
사용자, 자기소개 validation 적용
closes #112 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#112 사용자, 자기소개 validation 적용

.github/workflows/deploy-dev.yml, .github/workflows/validate.yml
- AWS S3 위에 개발서버를 올렸습니다. 
- 배포 주소 : http://team7-devnity-front-dev.s3-website.ap-northeast-2.amazonaws.com
- Github Actions에서 `develop` 브랜치에 push 감지시 `develop` 브랜치 코드를 빌드하여 결과물을 S3로 업로드합니다
- 기존 push, PR 감지시 lint, test를 진행하던 yml 파일을 하나로 합쳤습니다. (`validate.yml`)
closes #133 
- 확인하시고 머지시켜주세요!!
=> DVT-#133 개발 서버 CI/CD 설정 (AWS S3)

src/components/MapgakcoMap/MapgakcoMap.tsx, src/components/MapgakcoRegister/index.tsx, src/components/MapgakcoRegister/stlyes.ts, src/components/base/Button/index.tsx, src/components/base/Input/index.tsx, src/components/base/Input/types.ts, src/components/base/Modal/styles.ts, src/hooks/useMutationMapgakcoRegister.ts, src/utils/apis/mapgakco.ts
맵각코 등록 API 연동
closes #122 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 처음 화면 진입했을 때 (등록 버튼이 비활성화 되어 있음)
- 지도에 위치를 선택하면 등록 버튼이 활성화 됨
- 등록 버튼을 눌러 모달창에서 맵각코를 등록할 수 있음
- 맵각코 조회 API 완성되면 한번 알려주세요. 해당 react-query의 key 값이 필요합니다~!
=> DVT-#122 맵각코 등록

.github/workflows/deploy-dev.yml
.env 설정 추가 (DOMAIN)
closes #149 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#149 .env 개발서버 DOMAIN 추가

package.json, src/components/MapgakcoMap/MapgakcoMap.tsx, src/components/MapgakcoRegister/index.tsx, src/components/MapgakcoRegister/stlyes.ts, src/hooks/useToastUi.ts, yarn.lock
맵각코 피드백 반영
closes #145 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- react-datepicker 라이브러리 추가
- useToastUi 커스텀 훅에 markdown을 리셋하는 함수 추가
=> DVT-#145 맵각코 피드백 반영

src/components/GatherDetail/Comment/index.tsx, src/components/GatherDetail/Comment/styles.ts, src/components/GatherDetail/GatherDetail.tsx, src/components/GatherDetail/GatherDetailContainer.tsx, src/components/GatherDetail/styles.ts, src/components/GatherDetail/types.ts, src/components/PeriodText/index.tsx, src/constants/common.ts, src/constants/index.ts, src/hooks/useCloseGather.ts, src/hooks/useCreateGatherComment.ts, src/hooks/useDeleteComment.ts, src/hooks/useEditComment.ts, src/hooks/useGetGatherDetail.ts
모집 게시글의 댓글 레이아웃을 수정한다. 데둥이소개의 댓글을 가져다썼습니다.
closes #128 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
**삭제 버튼을 클릭할 시 확인 문구**
**수정 버튼을 누르기 전엔 편집 불가**
**수정 버튼을 눌렀을 때 편집할 수 있게 바뀌면 버튼 문구 변경**
**댓글**
=> DVT-#128 모집 게시글 댓글 레이아웃 수정

src/components/GatherDetail/GatherDetailContainer.tsx, src/components/Login/LoginContainer.tsx, src/components/MyProfile/MyProfile.tsx, src/components/MyProfile/styles.ts, src/components/Sidebar/Sidebar.test.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarContainer.test.tsx, src/components/Sidebar/menuRoutes.ts, src/components/Signup/Signup.tsx, src/components/Signup/SignupContainer.tsx, src/components/Signup/styles.ts, src/hooks/useQueryCheckValidLink.ts
closes #157 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#157 어드민이 생성한 회원가입 링크 정합성 체크 확인

src/assets/theme.ts, src/components/GatherMain/GatherMain.tsx, src/components/GatherRegisterForm/GatherRegisterForm.tsx, src/components/GatherRegisterForm/GatherRegistorFormContainer.tsx, src/components/GatherRegisterForm/styles.ts, src/hooks/useAddGather.ts
피드백 받은 모집 게시글 등록 모달을 수정한다.
closes #158 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/55550034/146778882-1d4108c9-4b21-470c-a173-69526f989ba0.mp4
없음
=> DVT-#158 모집게시판 게시글 등록 모달 수정

src/components/GatherDetail/Comment/index.tsx, src/components/GatherDetail/Comment/styles.ts, src/components/GatherDetail/GatherDetail.tsx, src/components/GatherDetail/styles.ts, src/components/UserDetail/styles.ts, src/hooks/useCreateGatherComment.ts, src/hooks/useDeleteComment.ts, src/hooks/useEditComment.ts
모집게시글 댓글 부분 수정
closes #159 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 작성 버튼 hover 색상은 따로 변경하지 않았습니다
- @rkdvnfma90 동일한 UI가 적용되는 데둥이소개 상세페이지의 댓글 작성 버튼 색상도 함께 변경해주었습니다!
=> DVT-#159 모집게시글 상세페이지 댓글 수정

src/assets/theme.ts, src/components/Main/styles.ts, src/components/ProfileCard/ProfileCard.tsx, src/components/Sidebar/styles.ts, src/components/UserCard/UserCard.tsx, src/components/UserCard/styles.ts, src/components/UserList/UserList.tsx, src/components/UserList/styles.ts, src/constants/common.ts, src/hooks/useMutationInviteLink.ts, src/hooks/useMutationUserDeleteComment.ts, src/hooks/useMutationUserDetailComment.ts, src/hooks/useQueryInviteLink.ts, src/hooks/useToastUi.ts, src/pages/MainPage/index.tsx, src/routes/Router.tsx, src/routes/customRoutes/RestrictRoute.tsx
전반적인 레이아웃 수정
closes #163 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 메인화면
- 사이드바 border 추가
- 카드디자인 변경 및 탑 내비게이션 바 색상 제거
- 여백 조절
- 데둥이 리스트 검색  form 디자인 변경 및 백엔드 태그 색상 변경
- 사항1
=> DVT-#163 레이아웃 수정

package.json, src/components/Admin/Admin.tsx, src/components/UsersMap/UsersMap.tsx, src/utils/apis/necessaryAuthAxiosInstance.ts, src/utils/apis/unnecessaryAuthAxiosInstance.ts, webpack.config.js
프로덕트 환경에 따른 API URL 환경 변수 설정
closes #174 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음 
없음
=> DVT-#174 프로덕트 환경에 따른 API URL 환경 변수 설정

src/App.tsx, src/components/Main/Main.test.tsx, src/components/Main/Main.tsx, src/components/Main/MainContainer.tsx, src/components/Main/MapgakcoSummary/MapgakcoSummaryContainer.tsx, src/components/Main/styles.ts, src/components/MapgakcoMap/MapgakcoMap.tsx
메인 페이지에 맵각코 요약 컴포넌트 렌더링
closes #178 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
더미데이터를 쓰던 맵각코 요약에서 실제 데이터로 변경했습니다.
없음. 중복되는 코드들은 리팩토링 기술 부채로 남겨둘게요...🥲
=> DVT-#178 메인 페이지에 맵각코 요약 컴포넌트 렌더링

package.json, src/components/Admin/Admin.tsx, yarn.lock
클립보드 버그 수정
closes #181 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#181 클립보드 버그 수정

src/components/MapgakcoMap/MapgakcoMap.tsx
맵각코 상세 정보에서 달력이 뭉개지는 현상을 고치기 위해 모달 너비 조절
closes #183 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
=> DVT-#183 맵각코 상세 정보에서 달력이 뭉개지는 현상을 고치기 위해 모달 너비 조절

src/components/UserCard/UserCard.tsx
DVT-#187 placeholder 이미지 추가
closes #187 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
=> DVT-#187 placeholder 이미지 추가

src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx, src/components/MapgakcoMap/MapgakcoMap.tsx, src/routes/Router.tsx
맵각코 상세 페이지 라우팅 연결
closes #191
> PR 양식 체크리스트
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/146973315-4c7c4d31-017d-442e-ab96-7bebf4679527.mov
없음
=> DVT-#191 맵각코 상세 페이지 라우팅 연결

src/components/UserCardList/UserCardList.tsx
메인화면 자기소개 가로스크롤 에러 수정
closes #198 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
- 일단 제 pc에선 제대로 동작하는데 여러분들 pc에서도 제대로 동작하는지 한번 확인 부탁드립니당
=> DVT-#198 메인화면 자기소개 에러 수정

src/assets/theme.ts, src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailContainer.tsx, src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx, src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/styles.ts, src/components/MapgakcoMap/MapgakcoDetail/styles.ts, src/components/MapgakcoMap/MapgakcoMap.tsx, src/components/MapgakcoMap/styles.ts
맵각코 상세 페이지에 작성자 구별 가능한 표시 추가
closes #200 
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/147168058-a19ae04e-1d87-43dd-923c-75579c7d54d6.mov
없음
=> DVT-#200 맵각코 상세 페이지를 모달에서 슬라이더로 변경 및 작성자 아이콘 추가

README.md
README 문서 작성
closes #205 
> 구현한 내용 체크리스트
=> README 문서 작성

src/components/UserImageAndDropdown/UserImageAndDropdown.tsx, src/components/UserImageAndDropdown/styles.ts
탑바 유저 드랍다운 메뉴에 UI 추가
closes #212 
> 구현한 내용 체크리스트
https://user-images.githubusercontent.com/8105528/148549496-e24e4154-6a02-43fd-bda9-d3ab01cf3d89.mov
- 넷플릭스 유저 드랍다운 메뉴를 참조했습니다.
=> DVT-#212 탑바 유저 드랍다운 메뉴에 드랍다운 UI 추가

src/components/CommentButton/CommentButton.tsx, src/components/GatherRegisterForm/GatherRegisterForm.tsx, src/components/LikeButton/LikeButton.tsx, src/components/Logo/Logo.tsx, src/components/Main/Main.tsx, src/components/MapgakcoMap/FilterButton.tsx, src/components/MapgakcoMap/MapFloatControl/index.tsx, src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnEdit/index.tsx, src/components/MapgakcoMap/MapgakcoDetail/MapgakcoDetailOnView/index.tsx, src/components/MyGather/MyGather.tsx, src/components/UserDetail/UserDetail.tsx, src/components/UserDetail/styles.ts, src/components/base/Button/styles.ts, src/components/base/Modal/index.tsx, src/components/base/OldButton/index.tsx, src/components/base/OldButton/styles.ts
버튼 컴포넌트 리팩토링
closes #219 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
없음
=> DVT-#219 버튼 컴포넌트 리팩토링

src/components/MapgakcoMap/FilterButton.tsx, src/components/MapgakcoMap/MapFloatControl/index.tsx, src/components/MapgakcoMap/MapFloatControl/styles.ts, src/components/MapgakcoMap/styles.ts
공통 버튼 컴포넌트를 사용하여 맵각코 지도 컨트롤 버튼을 리팩토링한다.
closes #221 
> PR 양식 체크리스트
> 구현한 내용 체크리스트
없음
=> DVT-#221 맵각코 지도 컨트롤 버튼 리팩토링
